name:                smap
version:             0.3.0
github:              "wyager/smap"
license:             BSD3
author:              "Will Yager"
maintainer:          "will@yager.io"
copyright:           "2019 Will Yager"
category:            Text
synopsis:            "A command line tool for working with sets and maps"

extra-source-files:
- README.md
- ChangeLog.md


description:         Please see the README below or on GitHub at <https://github.com/wyager/smap>

default-extensions:
- TupleSections
- RankNTypes
- ScopedTypeVariables
- LambdaCase
- BangPatterns
- KindSignatures
- DataKinds
- OverloadedStrings

dependencies:
- base >= 4.7 && < 5
- unordered-containers
- hashable
- attoparsec
- streaming
- streaming-bytestring
- bytestring
- resourcet
- optparse-applicative
- transformers
- strict
- text
- memory
- mmorph

library:
  source-dirs: src
  ghc-options:
  - -O2
  - -Wall
  - -fexpose-all-unfoldings
  - -optP-Wno-nonportable-include-path

executables:
  smap:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -rtsopts
    - -Wall
    - -O2
    - -fspecialize-aggressively
    - -optP-Wno-nonportable-include-path
    dependencies:
    - smap

tests:
  smap-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -rtsopts
    dependencies:
    - smap
